#!/bin/zsh
# make selected window into a dynamic scratchpad (become transparent when window does not have focus.)
# depends on xorg-xwininfo and set_wm_class
# Connor Rhodes (connorrhodes.com)

/home/connor/bin/set_wm_class $(xwininfo | grep "Window id:" | awk '{ print $4 }') dynamic-scratchpad dynamic-scratchpad
