add_newline = false

# disabled module
[package]
disabled = true

[cmd_duration]
disabled = true

# git
[git_branch]
symbol = ""
truncation_length = 6
truncation_symbol = ""

[git_commit]
disabled = true
