#!/bin/bash

xterm -e "pulseaudio -k"

sleep 1

sudo systemctl stop murmur.service 

sleep 1

killall mumble

# set up de-noised input

# switch laptop soundcard to use line-in mic
pacmd set-source-port alsa_input.pci-0000_05_00.6.analog-stereo analog-input-mic

noisetorch -s alsa_input.pci-0000_05_00.6.analog-stereo -i

# set denoised out as default mic
pacmd set-default-source nui_mic_denoised_out.monitor

notify-send "line-mic" "Ready"
