#!/bin/sh
# Script to set best microphone volume based on headset selected
# Connor Rhodes (connorrhodes.com)

CHOICE=$(echo "ENACFIRE E60\nSony WH-100XM3" | dmenu -fn 'Hack:normal:pixelsize=32')

case $CHOICE in
	"ENACFIRE E60")
		pacmd set-source-volume alsa_input.usb-0a12_Avantree_DG80-00.mono-fallback 100000
		;;
	"Sony WH-100XM3")
		pacmd set-source-volume alsa_input.usb-0a12_Avantree_DG80-00.mono-fallback 72000
		;;
esac
