#!/bin/sh

CHOICE=$(echo "enacfire_e60\nsony_wh-100xm3" | dmenu -fn 'Hack:normal:pixelsize=32')

case $CHOICE in
	enacfire_e60)
		pacmd set-source-volume alsa_input.usb-0a12_Avantree_DG80-00.mono-fallback 100000
		;;
	sony_wh-100xm3)
		pacmd set-source-volume alsa_input.usb-0a12_Avantree_DG80-00.mono-fallback 72000
		;;
esac
