#!/bin/bash
# Script to set up using phone as a microphone with a denoised mumble loopback
# Author: Connor Rhodes (connorrhodes.com)

pulseaudio -k

killall mumble

#sudo systemctl stop murmur.service

wmctrl -c Voice - Calls — Mozilla Firefox
wmctrl -c 100_Dictation - Google Docs

noisetorch -i # denoise default input
# sleep here?
pacmd set-default-source nui_mic_denoised_out.monitor

notify-send "gvoice-mic" "Ready"

winname="Voice - Calls — Mozilla Firefox"

winid=$(wmctrl -l | grep "$winname" | awk '{ print $1 }')

exec env GTK_THEME="Redmond97 Firefox Solaris" \
		/usr/lib/firefox/firefox -P App \
		--new-window https://voice.google.com/u/0/calls &
sleep 3 #might require some fiddling. It's the time it takes to launch google chrome

winid=$(wmctrl -l | grep "$winname" | awk '{ print $1 }')


wmctrl -r "$winname" -b add,hidden


# copy and clear out the dictation scratch

	WORK_DIR=$HOME/.cache/google-docs-dictation
	
	## ignore times is necessary to force a sync
	sleep .5
	rclone sync \
		--ignore-times \
		--drive-export-formats txt \
		personal_gdrive:100_Dictation.txt $WORK_DIR
	
	## fix whitespace issued created by pandoc odt conversion
	dos2unix $WORK_DIR/100_Dictation.txt
	## remove duplicate blank lines added in the conversion process
	sed -i '$!N; /^\(.*\)\n\1$/!P; D' $WORK_DIR/100_Dictation.txt
	
	xclip -r -selection clipboard -i $WORK_DIR/100_Dictation.txt 
	xclip -r -selection primary -i $WORK_DIR/100_Dictation.txt 
	
	sleep 1
	rclone sync \
		--ignore-times \
		--drive-export-formats odt \
		--drive-import-formats odt \
		$WORK_DIR/100_Dictation.odt personal_gdrive:
