#!/bin/bash
# Script to set up using phone as a microphone with a denoised mumble loopback
# Author: Connor Rhodes (connorrhodes.com)

# start mumble server
#sudo systemctl start murmur.service 

killall mumble

pulseaudio -k

wmctrl -c Voice - Calls — Mozilla Firefox

# Launch mumble client, move it to an unused workspace, and hide it.
winname="Mumble -- 1.3.4"

mumble mumble://laptop@localhost &

sleep 3

wmctrl -r "$winname" -b add,hidden

mumble rpc mute

# set up de-noised input

if [ -z "$(pacmd list-sources | grep "NoiseTorch Microphone")"  ]
then
	noisetorch -i # denoise default input

	sleep 3

fi
	~/bin/pulseout mumble ntmic

# set denoised out as default mic
pacmd set-default-source nui_mic_denoised_out.monitor

notify-send "phone-mic" "Ready"


winname="Voice - Calls — Mozilla Firefox"

winid=$(wmctrl -l | grep "$winname" | awk '{ print $1 }')

exec env GTK_THEME="Redmond97 Firefox Solaris" \
		/usr/lib/firefox/firefox -P App \
		--new-window https://voice.google.com/u/0/calls &
sleep 3 #might require some fiddling. It's the time it takes to launch google chrome

winid=$(wmctrl -l | grep "$winname" | awk '{ print $1 }')


wmctrl -r "$winname" -b add,hidden
