#!/bin/bash
# Script to set up using phone as a microphone with a denoised mumble loopback
# Author: Connor Rhodes (connorrhodes.com)

# start mumble server
# sudo systemctl start murmur.service 


# Launch mumble client, move it to an unused workspace, and hide it.
winname="Mumble -- 1.3.4"

mumble mumble://laptop@localhost &

sleep 3

wmctrl -r "$winname" -b add,hidden

mumble rpc mute

# set up de-noised input

if [ -z "$(pacmd list-sources | grep "NoiseTorch Microphone")"  ]
then
	noisetorch -i # denoise default input

	sleep 3

fi
	~/bin/pulseout mumble ntmic

# set denoised out as default mic
pacmd set-default-source nui_mic_denoised_out.monitor

notify-send "phone-mic" "Ready"
