#!/bin/sh
# script to record a voice note with high audio quality 
# and small file size for easy attachment using dwnrecent dmenu script
#
# Author: Connor Rhodes (connorrhodes.com)


# launch pavucontrol to verify mic volume
/home/connor/.local/dotfiles/shared/system_scripts/nopath/launch-pavucontrol.sh

ffmpeg -f pulse -ac 1 -i default -c:a libopus -b:a 40k -ar 16000 -application voip $HOME/dwn/$(date +"%Y-%m-%d_%H-%M-%S")_voice-note.opus

