#!/bin/sh
# script to convert and programatically rename chosen file to HEVC with ffmpeg.
# Author: Connor Rhodes

QUOTE=$(echo "$1" | sed 's/\\ / /g')

FILE=$(echo "$QUOTE" | sed 's/ /_/g' | sed 's/.mkv/_x265.mkv/g')

ffmpeg -i "$QUOTE" -vcodec libx265 -acodec libopus $FILE
