#!/bin/sh
# shell script to convert filenames in hexadecimal to ascii characters.
# useful for iwd filenames encoded in hex.
# The included regex matches filenames that begin with any character and 
# end with any extension but contain only hex characters in the middle.
# The script presents the ascii filenames with fzf for user selection
# and then outputs the hex filename corresponding to that choice.
#
# You can use this script in a shell alias such as: vhex='vim $(hexfiles)'
#
# Author: Connor Rhodes (connorrhodes.com)

REGEX="^.?[A-Fa-f0-9]+\.[A-Za-z0-9]+"
FILES=$(ls -1 | grep -E "$REGEX")

CACHE=$HOME/.cache/hexfiles.txt

rm $CACHE
touch $CACHE

for FILE in $FILES
do
	ASCII=$(echo $FILE | sed 's/\([0-9A-F]\{2\}\)/\\\\\\x\1/gI' | sed 's/=//g' | xargs printf)

	echo "$ASCII $FILE" >> $HOME/.cache/hexfiles.txt
done

CHOICE=$(awk '{ print $1 }' $CACHE | fzf)

HEXCHOICE=$(grep "$CHOICE" $CACHE | awk '{ print $2 }')

echo $HEXCHOICE
