#!/bin/bash
# Script to count down pomodoro work and rest intervals
# Original script by Bladtman242
# Modified by Connor Rhodes (connorrhodes.com) to: play custom sound, notifications, and output to tiling wm bar
# TODO integrate with time tracker

WORK=1
PAUSE=1
INTERACTIVE=true
MUTE=false

show_help() {
	cat <<-END
		usage: potato [-s] [-m] [-w m] [-b m] [-h]
		    -s: simple output. Intended for use in scripts
		        When enabled, potato outputs one line for each minute, and doesn't print the bell character
		        (ascii 007)

		    -m: mute -- don't play sounds when work/break is over
		    -w m: let work periods last m minutes (default is 25)
		    -b m: let break periods last m minutes (default is 5)
		    -h: print this message
	END
}

play_notification() {
	aplay -q /usr/lib/notifications/airplane_chime.wav&
	ref_bar
}

ref_bar() {
	kill $(pstree -lp | grep -- -baraction.sh | sed "s/.*sleep//" | sed "s/(//" | sed "s/)//") > /dev/null 2>&1
}

track_time() {
	read -p "utt add " TRACK	
	utt add "$TRACK"
}

while getopts :sw:b:m opt; do
	case "$opt" in
	s)
		INTERACTIVE=false
	;;
	m)
		MUTE=true
	;;
	w)
		WORK=$OPTARG
	;;
	b)
		PAUSE=$OPTARG
	;;
	h|\?)
		show_help
		exit 1
	;;
	esac
done

time_left="%im left of %s "

if $INTERACTIVE; then
	time_left="\r$time_left"
	ref_bar
else
	time_left="$time_left\n"
	ref_bar
fi

while true
do
	for ((i=$WORK; i>0; i--))
	do
		printf "$time_left" $i "work" | tee | sed "s/\r//g" | awk '{ print $1}' | tee /home/connor/.cache/pomodoro-time.txt
		ref_bar
		sleep 1m
	done

	! $MUTE && play_notification && ref_bar
	if $INTERACTIVE; then
		read -d '' -t 0.001
		echo -e "\a"
		echo "Work over" | tee /home/connor/.cache/pomodoro-time.txt
		notify-send -u critical Pomodoro "Work Over"
		ref_bar
		track_time	
	fi

	for ((i=$PAUSE; i>0; i--))
	do
		printf "$time_left" $i "pause"
		ref_bar
		sleep 1m
	done

	! $MUTE && play_notification
	if $INTERACTIVE; then
		read -d '' -t 0.001
		echo -e "\a"
		echo "Break over" | tee /home/connor/.cache/pomodoro-time.txt
		ref_bar
		notify-send -u critical Pomodoro "Break over"
		track_time
	fi
done
