#!/bin/sh
# this script uses GNU Stow to update all symlinks throughout the filesystem.
# Connor Rhodes (connorrhodes.com)

# shared
cd /home/connor/.local/dotfiles/shared/stow_user
stow -R -t /home/connor * 2>&1 | grep -A 2 -E "^WARNING"

cd /home/connor/.local/dotfiles/shared/stow_root
sudo stow -R -t / * 2>&1 | grep -A 2 -E "^WARNING"

cd /home/connor/.local/dotfiles_secret/shared/stow_user
stow -R -t /home/connor * 2>&1 | grep -A 2 -E "^WARNING"

# machine-specific
cd /home/connor/.local/dotfiles/$(hostname)/stow_user
stow -R -t /home/connor * 2>&1 | grep -A 2 -E "^WARNING"

cd /home/connor/.local/dotfiles/$(hostname)/stow_root
sudo stow -R -t / * 2>&1 | grep -A 2 -E "^WARNING"

cd /home/connor/.local/dotfiles_secret/$(hostname)/stow_user/symlinked
stow -R -t /home/connor * 2>&1 | grep -A 2 -E "^WARNING"

cd /home/connor/.local/dotfiles_secret/$(hostname)/stow_root
sudo stow -R -t / * 2>&1 | grep -A 2 -E "^WARNING"

#cd /home/connor/.local/dotfiles_secret/$(hostname)/stow_user/adopted
#stow -R --adopt -t /home/connor * 2>&1 | grep -A 2 -E "^WARNING"
