#!/bin/sh

NEWFILE=$(echo "$1" | sed 's/\\ / /g' | sed 's/.mkv/_nosilence.mkv/g')

unsilence -y -t 6 -sv 1 -ss 4 -sl -50 -st .30 "$1" "$NEWFILE"

# sl for silcence level
# 45 cuts some non-silence (with noisetorch)
