#!/bin/bash
# script to allow my to pipe text into all X11 clipboards simultaneously
# Connor Rhodes (connorrhodes.com)

[[ -p /dev/stdin ]] && { mapfile -t; set -- "${MAPFILE[@]}"; }

for i in "$@"; do
    printf "$i" | xclip -selection primary
    printf "$i" | xclip -selection secondary
    printf "$i" | xclip -selection clipboard
done
